using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ErpConnector.Ax.DTO
{
    public class PurchTableDTO
    {
        public long RecId { get; set; }
        public string DataAreaId { get; set; }
        public long Partition { get; set; }
        public int RecVersion { get; set; }
        public string OrderAccount { get; set; }
        public string LineDisc { get; set; }
        public DateTime AccountingDate { get; set; }
        public long AccountingDistributionTemplate { get; set; }
        public long AddressRefRecId { get; set; }
        public int AddressRefTableId { get; set; }
        public int AutoSummaryModuleType { get; set; }
        public DateTime AvailSalesDate { get; set; }
        public string BankCentralBankPurposeCode { get; set; }
        public string BankCentralBankPurposeText { get; set; }
        public int BankDocumentType { get; set; }
        public string CashDisc { get; set; }
        public decimal CashDiscPercent { get; set; }
        public int ChangeRequestRequired { get; set; }
        public DateTime ConfirmedDlv { get; set; }
        public DateTime ConfirmedDlvEarliest { get; set; }
        public long ConfirmingPO { get; set; }
        public int ConsTarget_JP { get; set; }
        public string ContactPersonId { get; set; }
        public string ContractNum_SA { get; set; }
        public string CountryOrigDest { get; set; }
        public int CovStatus { get; set; }
        public DateTime CrossDockingDate { get; set; }
        public string CurrencyCode { get; set; }
        public long DefaultDimension { get; set; }
        public DateTime DeliveryDate { get; set; }
        public string DeliveryName { get; set; }
        public long DeliveryPostalAddress { get; set; }
        public int DeliveryType { get; set; }
        public long DiscPercent { get; set; }
        public string DlvMode { get; set; }
        public string DlvTerm { get; set; }
        public int DocumentState { get; set; }
        public int DocumentStatus { get; set; }
        public string Email { get; set; }
        public string EndDisc { get; set; }
        public string EnterpriceNumber { get; set; }
        public DateTime ExcangeRateDate { get; set; }
        public DateTime FinalizeClosingDate { get; set; }
        public DateTime FixedDueDate { get; set; }
        public long FixedExchRate { get; set; }
        public int FreightSlipTyp { get; set; }
        public string FreightZone { get; set; }
        public int FSHAutoCreated { get; set; }
        public int InclTax { get; set; }
        public int InterCompanyAllowIndirectCreation { get; set; }
        public string InterCompanyCompanyId { get; set; }
        public string InterCompanyCustPurchOrderFormNum { get; set; }
        public int InterCompanyDirectDelivery { get; set; }
        public int InterCompanyOrder { get; set; }
        public int InterCompanyOrigin { get; set; }
        public string InterCompanyOriginalCustAccount { get; set; }
        public string InterCompanyOriginalSalesId { get; set; }
        public string InterCompanySalesId { get; set; }
        public decimal IntrastatAddValue_LV { get; set; }
        public DateTime IntrastatFulfillmentDate_HU { get; set; }
        public string InventLocationId { get; set; }
        public string InventSiteId { get; set; }
        public string InvoiceAccount { get; set; }
        public int InvoiceAutoNumbering_LT { get; set; }
        public int IsEnumbranceRequired { get; set; }
        public int IsModified { get; set; }
        public string ItemBuyerGroupId { get; set; }
        public string LanguageId { get; set; }
        public int ListCode { get; set; }
        public DateTime LocalDeliveryDate { get; set; }
        public long ManualEntryChangepolicy { get; set; }
        public string MarkupGroup { get; set; }
        public long MatchingAgreement { get; set; }
        public int MCRDropShipment { get; set; }
        public string MultiLineDisc { get; set; }
        public string NumberSequenceGroup { get; set; }
        public int OneTimeSupplier { get; set; }
        public int OneTimeVendor { get; set; }
        public int PackingSlipAutoNumbering_LT { get; set; }
        public string Payment { get; set; }
        public string PaymentSched { get; set; }
        public string PaymMode { get; set; }
        public string PaymSpec { get; set; }
        public string Port { get; set; }
        public string PostingProfile { get; set; }
        public string PriceGroupId { get; set; }
        public string ProjId { get; set; }
        public int PurchaseType { get; set; }
        public string PurchId { get; set; }
        public string PurchName { get; set; }
        public string PurchPoolId { get; set; }
        public int PurchStatus { get; set; }
        public long ReasonTableRef { get; set; }
        public DateTime ReceiptDateConfirmed { get; set; }
        public string ReplensihmentLocation { get; set; }
        public string ReqAttention { get; set; }
        public long Requester { get; set; }
        public string RetailDriverDetails { get; set; }
        public int RetailRetailStatusType { get; set; }
        public string ReturnItemNum { get; set; }
        public string ReturnReasonCodeId { get; set; }
        public int ReturnReplacementCreated { get; set; }
        public string ServiceAddress { get; set; }
        public string ServiceCategory { get; set; }
        public DateTime ServiceDate { get; set; }
        public string ServiceName { get; set; }
        public int SettleVoucher { get; set; }
        public DateTime ShippingDateConfirmed { get; set; }
        public DateTime ShippingDateRequested { get; set; }
        public long SourceDocumentHeader { get; set; }
        public long SourceDocumentLine { get; set; }
        public string StatProcId { get; set; }
        public long SystemEntryChangePolicy { get; set; }
        public int SystemEntrySource { get; set; }
        public string TAMVendRebateGroupId { get; set; }
        public string TaxGroup { get; set; }
        public string TaxPeriodPaymentCode_PL { get; set; }
        public string TransactionCode { get; set; }
        public string Transport { get; set; }
        public long TransportationDocument { get; set; }
        public int UnitedVATInvoice_LT { get; set; }
        public string URL { get; set; }
        public string VATNum { get; set; }
        public string VendGroup { get; set; }
        public long VendInvoiceDeclaration_IS { get; set; }
        public string VendorRef { get; set; }
        public long WorkerPurchPlacer { get; set; }
        public int SkipCreateMarkup { get; set; }
        public int SkipVersioning { get; set; }
        public int SkipUpdate { get; set; }
        public int PurchaseOrderHeaderCreationMethod { get; set; }
        public int InvoiceRegister_LT { get; set; }
        public int PackingSlipRegister_LT { get; set; }
    }
}
