using System;
using ErpConnector.Ax.Microsoft.Dynamics.DataEntities;

namespace ErpConnector.Ax.DTO
{
    public class ReleasedDistinctProductsWriteDTO
    {
        public string AlternativeItemNumber { get; set; }
        public string AlternativeProductColorId { get; set; }
        public string AlternativeProductConfigurationId { get; set; }
        public string AlternativeProductSizeId { get; set; }
        public string AlternativeProductStyleId { get; set; }
        public ItemNumAlternative AlternativeProductUsageCondition { get; set; }
        public PdsVendorCheckItem ApprovedVendorCheckMethod { get; set; }
        public decimal ApproximateSalesTaxPercentage { get; set; }
        public NoYes AreTransportationManagementProcessesEnabled { get; set; }
        public int ArrivalHandlingTime { get; set; }
        public string BarcodeSetupId { get; set; }
        public SalesPriceModelBasic BaseSalesPriceSource { get; set; }
        public InventBatchMergeDateCalculationMethod BatchMergeDateCalculationMethod { get; set; }
        public string BatchNumberGroupCode { get; set; }
        public int BestBeforePeriodDays { get; set; }
        public string BOMUnitSymbol { get; set; }
        public string BuyerGroupId { get; set; }
        public ABC CarryingCostABCCode { get; set; }
        public string CatchWeightUnitSymbol { get; set; }
        public string CommissionProductGroupId { get; set; }
        public string ComparisonPriceBaseUnitSymbol { get; set; }
        public decimal ConstantScrapQuantity { get; set; }
        public int ContinuityEventDuration { get; set; }
        public string ContinuityScheduleId { get; set; }
        public string CostCalculationGroupId { get; set; }
        public decimal CostChargesQuantity { get; set; }
        public string CostGroupId { get; set; }
        //public string DataAreaId { get; set; }
        public string DefaultDirectDeliveryWarehouse { get; set; }
        public string DefaultLedgerDimensionDisplayValue { get; set; }
        public ReqPOType DefaultOrderType { get; set; }
        public decimal DefaultReceivingQuantity { get; set; }
        public decimal FixedCostCharges { get; set; }
        public decimal FixedPurchasePriceCharges { get; set; }
        public decimal FixedSalesPriceCharges { get; set; }
        public ProdFlushingPrincipItem FlushingPrinciple { get; set; }
        public string FreightAllocationGroupId { get; set; }
        public decimal GrossDepth { get; set; }
        public decimal GrossProductHeight { get; set; }
        public decimal GrossProductWidth { get; set; }
        public decimal IntrastatChargePercentage { get; set; }
        public string IntrastatCommodityCode { get; set; }
        //public string InventoryGSTReliefCategoryCode { get; set; }
        public string InventoryReservationHierarchyName { get; set; }
        public string InventoryUnitSymbol  { get; set; }
        public NoYes IsDeliveredDirectly { get; set; }
        public NoYes IsDiscountPOSRegistrationProhibited { get; set; }
        public NoYes IsExemptFromAutomaticNotificationAndCancellation { get; set; }
        public NoYes IsICMSTaxAppliedOnService { get; set; }
        public NoYes IsInstallmentEligible { get; set; }
        public NoYes IsIntercompanyPurchaseUsageBlocked { get; set; }
        public NoYes IsIntercompanySalesUsageBlocked { get; set; }
        public NoYes IsPhantom { get; set; }
        public NoYes IsPOSRegistrationBlocked { get; set; }
        public NoYes IsPOSRegistrationQuantityNegative { get; set; }
        public NoYes IsPurchasePriceAutomaticallyUpdated { get; set; }
        public NoYes IsPurchasePriceIncludingCharges { get; set; }
        public NoYes IsPurchaseWithholdingTaxCalculated { get; set; }
        public NoYes IsRestrictedForCoupons { get; set; }
        public NoYes IsSalesPriceAdjustmentAllowed { get; set; }
        public NoYes IsSalesPriceIncludingCharges { get; set; }
        public NoYes IsSalesWithholdingTaxCalculated { get; set; }
        public NoYes IsScaleProduct { get; set; }
        public NoYes IsShipAloneEnabled { get; set; }
        public NoYes IsUnitCostAutomaticallyUpdated { get; set; }
        public NoYes IsUnitCostIncludingCharges { get; set; }
        public NoYes IsVariantShelfLabelsPrintingEnabled { get; set; }
        public NoYes IsZeroPricePOSRegistrationAllowed { get; set; }
        public string ItemFiscalClassificationCode { get; set; }
        public string ItemFiscalClassificationExceptionCode { get; set; }
        public string ItemModelGroupId { get; set; }
        public string ItemNumber { get; set; }
        public RetailPriceKeyingRequirement KeyInPriceRequirementsAtPOSRegister { get; set; }
        public RetailQtyKeyingRequirement KeyInQuantityRequirementsAtPOSRegister { get; set; }
        public ABC MarginABCCode { get; set; }
        public decimal MaximumCatchWeightQuantity { get; set; }
        public decimal MaximumPickQuantity { get; set; }
        public decimal MinimumCatchWeightQuantity { get; set; }
        public NoYes MustKeyInCommentAtPOSRegister { get; set; }
        public string NecessaryProductionWorkingTimeSchedulingPropertyId { get; set; }
        public decimal NetProductWeight { get; set; }
        public int NGPCode { get; set; }
        public string OriginCountryRegionId { get; set; }
        public string OriginStateId { get; set; }
        public string PackageClassId { get; set; }
        public int PackageHandlingTime { get; set; }
        public decimal PackingDutyQuantity { get; set; }
        public string PackingMaterialGroupId { get; set; }
        public string PackSizeCategoryId { get; set; }
        public string PhysicalDimensionGroupId { get; set; }
        public string PlanningFormulaItemNumber { get; set; }
        public DateTimeOffset POSRegistrationActivationDate { get; set; }
        public DateTimeOffset POSRegistrationBlockedDate { get; set; }
        public DateTimeOffset POSRegistrationPlannedBlockedDate { get; set; }
        public decimal PotencyBaseAttibuteTargetValue { get; set; }
        public string PotencyBaseAttributeId { get; set; }
        public PDSPotencyAttribRecordingEnum PotencyBaseAttributeValueEntryEvent { get; set; }
        public string PrimaryVendorAccountNumber { get; set; }
        public string ProductCoverageGroupId { get; set; }
        public string ProductFiscalInformationType { get; set; }
        public string ProductGroupId { get; set; }
        public decimal ProductionConsumptionDensityConversionFactor { get; set; }
        public decimal ProductionConsumptionDepthConversionFactor { get; set; }
        public decimal ProductionConsumptionHeightConversionFactor { get; set; }
        public decimal ProductionConsumptionWidthConversionFactor { get; set; }
        public string ProductionGroupId { get; set; }
        public string ProductionPoolId { get; set; }
        public PmfProductType ProductionType { get; set; }
        public string ProductLifeCycleSeasonCode { get; set; }
        public DateTimeOffset ProductLifeCycleValidFromDate { get; set; }
        public DateTimeOffset ProductLifeCycleValidToDate { get; set; }
        public string ProductNumber { get; set; }
        public FITaxationOrigin_BR ProductTaxationOrigin { get; set; }
        public decimal ProductVolume { get; set; }
        public string ProjectCategoryId { get; set; }
        public string PurchaseChargeProductGroupId { get; set; }
        public decimal PurchaseChargesQuantity { get; set; }
        //public string PurchaseGSTReliefCategoryCode { get; set; }
        public string PurchaseItemWithholdingTaxGroupCode { get; set; }
        public string PurchaseLineDiscountProductGroupCode { get; set; }
        public string PurchaseMultilineDiscountProductGroupCode { get; set; }
        public decimal PurchaseOverdeliveryPercentage { get; set; }
        public decimal PurchasePrice { get; set; }
        public DateTimeOffset PurchasePriceDate { get; set; }
        public decimal PurchasePriceQuantity { get; set; }
        public string PurchasePriceToleranceGroupId { get; set; }
        public int PurchasePricingPrecision { get; set; }
        public string PurchaseRebateProductGroupId { get; set; }
        public string PurchaseSalesTaxItemGroupCode { get; set; }
        public string PurchaseSupplementaryProductProductGroupId { get; set; }
        public decimal PurchaseUnderdeliveryPercentage { get; set; }
        public string PurchaseUnitSymbol { get; set; }
        public WHSAllowMaterialOverPick RawMaterialPickingPrinciple { get; set; }
        public ABC RevenueABCCode { get; set; }
        public string SalesChargeProductGroupId { get; set; }
        public decimal SalesChargesQuantity { get; set; }
        //public string SalesGSTReliefCategoryCode = null; // cannot insert for the given value
        public string SalesItemWithholdingTaxGroupCode { get; set; }
        public string SalesLineDiscountProductGroupCode { get; set; }
        public string SalesMultilineDiscountProductGroupCode { get; set; }
        public decimal SalesOverdeliveryPercentage { get; set; }
        public decimal SalesPrice { get; set; }
        public decimal SalesPriceCalculationChargesPercentage { get; set; }
        public decimal SalesPriceCalculationContributionRatio { get; set; }
        public SalesPriceModel SalesPriceCalculationModel { get; set; }
        public DateTimeOffset SalesPriceDate { get; set; }
        public decimal SalesPriceQuantity { get; set; }
        public int SalesPricingPrecision { get; set; }
        public string SalesRebateProductGroupId { get; set; }
        public string SalesSalesTaxItemGroupCode { get; set; }
        public string SalesSupplementaryProductProductGroupId { get; set; }
        public decimal SalesUnderdeliveryPercentage { get; set; }
        public string SalesUnitSymbol { get; set; }
        public string SearchName { get; set; }
        public DateTimeOffset SellEndDate { get; set; }
        public DateTimeOffset SellStartDate { get; set; }
        public string SerialNumberGroupCode { get; set; }
        public string ServiceFiscalInformationCode { get; set; }
        public int ShelfAdvicePeriodDays { get; set; }
        public int ShelfLifePeriodDays { get; set; }
        public int ShippingAndReceivingSortOrderCode { get; set; }
        public DateTimeOffset ShipStartDate { get; set; }
        public string StorageDimensionGroupName { get; set; }
        public decimal TareProductWeight { get; set; }
        public string TrackingDimensionGroupName { get; set; }
        public decimal TransferOrderOverdeliveryPercentage { get; set; }
        public decimal TransferOrderUnderdeliveryPercentage { get; set; }
        public string UnitConversionSequenceGroupId { get; set; }
        public decimal UnitCost { get; set; }
        public DateTimeOffset UnitCostDate { get; set; }
        public int UnitCostQuantity { get; set; }
        public ABC ValueABCCode { get; set; }
        public decimal VariableScrapPercentage { get; set; }
        public PurchMatchingPolicyWithNotSetOption VendorInvoiceLineMatchingPolicy { get; set; }
        public string WarehouseMobileDeviceDescriptionLine1 { get; set; }
        public string WarehouseMobileDeviceDescriptionLine2 { get; set; }
        public NoYes WillInventoryIssueAutomaticallyReportAsFinished { get; set; }
        public NoYes WillInventoryReceiptIgnoreFlushingPrinciple { get; set; }
        public NoYes WillPickingWorkbenchApplyBoxingLogic { get; set; }
        public NoYes WillTotalPurchaseDiscountCalculationIncludeProduct { get; set; }
        public NoYes WillTotalSalesDiscountCalculationIncludeProduct { get; set; }
        public NoYes WillWorkCenterPickingAllowNegativeInventory { get; set; }
        public decimal YieldPercentage { get; set; }

    }
}
